### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by dsoprea** [tcurdt/uif2iso4mac#1]
How do you build this project from the command-line? It would be useful to document this.

Thank you.

**Comment by tcurdt** [comment]
If you are into the command line you can just use command line tool directly 

  http://aluigi.altervista.org/mytoolz.htm

Otherwise you will need Xcode (although build from the command line is possible with Xcode, too). The project might need some updates though. It's been a while since the last release.

**Comment by dsoprea** [comment]
This is a Mac tool and the download is an EXE. I need something that will run on a Mac. I'm asking how to build from the command-line. The Xcode tools are available but there doesn't appear to be a scheme defined such that I can call `xcodebuild`. I'm really not familiar with building Xcode projects, so I'd appreciate a little assistance to help me build this. Then, either you or I can update the README with the command in the interest of helping others with this.

**Comment by tcurdt** [comment]
The download from aluigi also includes the source that you can build from the command line.

I've pushed some unrelated updates so we are on the same page but `uif2iso4mac` also builds fine for me with `xcodebuild`.

**Comment by dsoprea** [comment]
I'd rather use Github for the sourcecode. Otherwise, I can't be sure which version of the code that I'm dealing with.

Please give me the command to build [with the code from Github]. As stated, I'm unfamiliar with Xcode.

**Comment by tcurdt** [comment]
And I rather have a pony.

Here is the build script and even the compiled command line tool:

https://github.com/tcurdt/uif2iso4mac/tree/master/Resources
